apiVersion: v1
kind: ConfigMap
metadata:
  name: scraper-config
  namespace: production
data:
  PROJECT_ID: "reliabledashboard"
  REDIS_HOST: "redis-service.production.svc.cluster.local"
  REDIS_PORT: "6379"
  BASE_URL: "https://www.reliableparts.com"
  RATE_LIMIT_REQUESTS: "10"
  RATE_LIMIT_PERIOD: "60"
  PROMETHEUS_PORT: "8000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper
  template:
    metadata:
      labels:
        app: scraper
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: scraper
        image: us-central1-docker.pkg.dev/reliabledashboard/reliableparts-images/scraper:v8
        envFrom:
        - configMapRef:
            name: scraper-config
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: url
        ports:
        - name: metrics
          containerPort: 8000
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30